"""Second-round revision (Reviewer 1, Comment 2): rebuild manuscript
Table 8 (coefficient sensitivity) from the archived summary
results/rev/sensitivity_summary.json, adding, in parentheses, the
percentage change of every indicator relative to the 1x reference of
the same sweep. Reads the archived summary only; trains and evaluates
nothing, and reproduces every previously reported number unchanged.

Usage:  python scripts/rev/rev15_table08_pct.py
Writes: results/rev/table08_sensitivity.tex
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__),
                                                "..", "..")))
from scripts.rev.rev_common import OUT  # noqa: E402

# (json key, decimals, compare across peak-weight rows?)
COLS = [("bill", 1, True), ("objective", 1, None),
        ("throughput_kwh", 0, True), ("efc", 2, True),
        ("peak_import_kw", 0, True)]
REVCMD = "\\revtwo"   # blue in the round-2 manuscript; \providecommand'ed below


def _pct(v: float, ref: float) -> str:
    d = 100.0 * (v / ref - 1.0)
    return "($%+.1f\\%%$)" % d


def _cell(r, ref, key, dec, comparable, is_ref):
    """value + blue tag: (ref.) on the 1x row, (--) where the indicator is
    not comparable across rows (objective, peak-weight sweep), else the
    signed percentage change relative to the reference row."""
    val = ("%%.%df" % dec) % r[key]
    if is_ref:
        tag = "(ref.)"
    elif comparable is None and r["_sweep"] != "lam1":
        tag = "(--)"
    else:
        tag = _pct(r[key], ref[key])
    return "%s %s{%s}" % (val, REVCMD, tag)


def block(rows, sym):
    ref = next(r for r in rows if float(r["factor"]) == 1.0)
    out = []
    for r in rows:
        is_ref = float(r["factor"]) == 1.0
        cells = [_cell(r, ref, k, d, c, is_ref) for (k, d, c) in COLS]
        out.append("%s$\\times %g$ & %d & %s \\\\"
                   % (sym, r["factor"], int(r["n_seeds"]), " & ".join(cells)))
    return "\n".join(out)


def write_table08(summary: dict, out_tex: str) -> str:
    for sweep in ("lam1", "lampk"):
        for r in summary[sweep]:
            r["_sweep"] = sweep
    tex = (
        "% Added in the first revision (Reviewer 1, Comments 3 and 4):\n"
        "% degradation- and peak-weight sensitivity on the 30 winter-weekday\n"
        "% test days. Second revision (Reviewer 1, Comment 2): percentage\n"
        "% change relative to the 1x reference of each sweep, in parentheses\n"
        "% (blue). Generated by scripts/rev/rev15_table08_pct.py from\n"
        "% results/rev/sensitivity_summary.json; no number changed.\n"
        "\\providecommand{\\revtwo}[1]{#1}\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Sensitivity of held-out operation to the degradation\n"
        "coefficient $\\lambda_1$ and the peak weight $\\lambda_{\\mathrm{pk}}$.\n"
        "Each variant is retrained from scratch at the stated coefficient\n"
        "(identical pilot-frozen budgets; winter-weekday regime) and evaluated\n"
        "on the same 30 held-out winter-weekday test days; factor $1\\times$ is\n"
        "the primary calibrated model. Bill and objective in GBP/day (the\n"
        "objective is evaluated under each variant's own coefficients, so\n"
        "objectives are not comparable across peak-weight rows); throughput in\n"
        "kWh/day. All runs record zero SoC violations. " + REVCMD + "{Values in\n"
        "parentheses give the percentage change of each indicator relative to\n"
        "the $1\\times$ reference row (ref.) of the same sweep; they are omitted\n"
        "(--) for the objective in the peak-weight sweep for the reason just\n"
        "stated.}}\n"
        "\\label{tab:sensitivity}\n"
        "\\small\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        "\\begin{tabular}{lcccccc}\n\\toprule\n"
        "Variant & Seeds & Bill & Objective & Throughput & EFC & Peak (kW) \\\\\n"
        "\\midrule\n"
        + block(summary["lam1"], "$\\lambda_1$") + "\n\\midrule\n"
        + block(summary["lampk"], "$\\lambda_{\\mathrm{pk}}$") + "\n"
        "\\bottomrule\n\\end{tabular}}\n\\end{table}\n")
    with open(out_tex, "w", encoding="utf-8", newline="\n") as f:
        f.write(tex)
    print("saved", out_tex)
    return tex


def main() -> int:
    with open(os.path.join(OUT, "sensitivity_summary.json")) as f:
        summary = json.load(f)
    tex = write_table08(summary, os.path.join(OUT, "table08_sensitivity.tex"))
    print(tex)
    return 0


if __name__ == "__main__":
    sys.exit(main())
