"""Generate all publication figures from the immutable results master and
the dedicated raw files. Each figure saves PDF + 600 dpi PNG + source data.
Figures with missing inputs are skipped with a warning (recorded)."""
from __future__ import annotations

import argparse
import json
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from src.latex_export import load_master                 # noqa: E402
from src.plotting import (METHOD_STYLE, panel_label,     # noqa: E402
                          qa_check, save_figure, set_style)

RAW = os.path.join(ROOT, "results", "raw")
skipped = []


def sty(m):
    return METHOD_STYLE.get(m, dict(color="#333333", ls="-", marker="",
                                    label=m))


# ----------------------------------------------------------------------
def fig01():
    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    ax.axis("off")

    def box(x, y, w, h, text, fc="#EEF3FA", ec="#4477AA"):
        ax.add_patch(plt.Rectangle((x, y), w, h, fc=fc, ec=ec, lw=1.2,
                                   zorder=2, joinstyle="round"))
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
                fontsize=8, zorder=3)

    # Revision (Reviewer 1, Comment 2): arrow labels take explicit
    # offsets (tdx, tdy) so no variable overlaps a line or arrow.
    def arrow(x0, y0, x1, y1, text="", color="#333333", ls="-",
              tdx=0.0, tdy=0.02):
        ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                    arrowprops=dict(arrowstyle="-|>", color=color, lw=1.2,
                                    linestyle=ls))
        if text:
            ax.text((x0 + x1) / 2 + tdx, (y0 + y1) / 2 + tdy, text,
                    ha="center", fontsize=7, color=color, zorder=4)

    box(0.02, 0.62, 0.17, 0.25, "Renewable\ngeneration $R_t$",
        fc="#E8F5E9", ec="#009E73")
    box(0.02, 0.15, 0.17, 0.25, "Local demand\n$L_t$", fc="#FFF3E0",
        ec="#E69F00")
    box(0.30, 0.38, 0.16, 0.26, "Net load\n$N_t = L_t - R_t$\n$=\\bar n_r(t)+Y_t$")
    box(0.56, 0.62, 0.18, 0.26, "Utility grid\n$G_t=N_t-A_t$\nprice $\\bar c_r(t)+P_t$",
        fc="#FCE4EC", ec="#CC79A7")
    box(0.56, 0.10, 0.18, 0.26, "Battery $S_t$\n$A_t>0$: discharge\n$A_t<0$: charge",
        fc="#E3F2FD", ec="#0072B2")
    box(0.80, 0.36, 0.185, 0.30,
        "Feedback controller\n$A_t=\\pi(t,S_t,Y_t,P_t)$\nsafe set "
        "$\\mathcal{A}(s)\\cap\\mathcal{A}_\\Delta(s)$",
        fc="#FFF8E1", ec="#D55E00")
    arrow(0.19, 0.74, 0.30, 0.56)
    arrow(0.19, 0.28, 0.30, 0.46)
    arrow(0.46, 0.55, 0.56, 0.68, "$N_t$", tdx=-0.025, tdy=0.03)
    arrow(0.65, 0.36, 0.65, 0.62, "$A_t$", tdx=-0.035, tdy=0.0)
    arrow(0.74, 0.33, 0.80, 0.44, "$S_t$", color="#0072B2", ls="--",
          tdx=-0.005, tdy=0.045)
    arrow(0.74, 0.70, 0.86, 0.66, "$Y_t,P_t$", color="#CC79A7", ls="--",
          tdx=0.0, tdy=0.045)
    arrow(0.88, 0.36, 0.74, 0.185, "$A_t$", color="#D55E00",
          tdx=0.045, tdy=-0.005)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    save_figure(fig, "fig01_microgrid_control_architecture",
                {"description": "system schematic; generated by code",
                 "sign_convention": "A>0 discharge, A<0 charge",
                 "grid_exchange": "G = N - A"})


def fig02():
    # Second revision (Reviewer 1, Comment 1): every arrow is a straight or
    # orthogonal (elbow) polyline, and each label is centred on a segment of
    # its own arrow with one uniform clearance (GAP), so no label can be read
    # as belonging to a neighbouring arrow. The policy loop is routed above
    # the top row and the stopping-test arrow enters the policy-evaluation
    # block through its own elbow (no crossings). Box contents unchanged.
    fig, ax = plt.subplots(figsize=(7.2, 3.9))
    ax.axis("off")
    LW, COL, GAP, FS = 1.2, "#333333", 0.022, 7

    def box(x, y, w, h, text, fc="#EEF3FA", ec="#4477AA"):
        ax.add_patch(plt.Rectangle((x, y), w, h, fc=fc, ec=ec, lw=1.2,
                                   zorder=2))
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
                fontsize=8, zorder=3)

    def arrow(pts, text="", seg=0, side=+1, color=COL):
        """Polyline arrow through pts (arrowhead on the last segment). A
        label is centred on segment `seg` and offset by GAP perpendicular
        to it (side=+1: above a horizontal / right of a vertical segment)."""
        xs, ys = zip(*pts)
        if len(pts) > 2:
            ax.plot(xs[:-1], ys[:-1], color=color, lw=LW,
                    solid_joinstyle="miter", zorder=1)
        ax.annotate("", xy=pts[-1], xytext=pts[-2],
                    arrowprops=dict(arrowstyle="-|>", color=color, lw=LW,
                                    shrinkA=0, shrinkB=0))
        if text:
            (x0, y0), (x1, y1) = pts[seg], pts[seg + 1]
            xm, ym = (x0 + x1) / 2, (y0 + y1) / 2
            if abs(y1 - y0) < 1e-9:          # horizontal segment
                ax.text(xm, ym + side * GAP, text, ha="center",
                        va="bottom" if side > 0 else "top",
                        fontsize=FS, color=color, zorder=4)
            else:                            # vertical segment
                ax.text(xm + side * GAP, ym, text,
                        ha="left" if side > 0 else "right", va="center",
                        fontsize=FS, color=color, zorder=4)

    # top row: the policy-iteration loop; bottom row: the disjoint point sets
    box(0.02, 0.62, 0.20, 0.26, "Policy evaluation\nPINN solves linear\n"
        "$\\partial_t v+\\mathcal{L}^{\\pi_n}v+\\ell^{\\pi_n}=0$\n"
        "(hard terminal)", fc="#E3F2FD", ec="#0072B2")
    box(0.28, 0.62, 0.20, 0.26, "Residual-adaptive\nrefinement\n"
        "(candidate pool,\ntop quantile)", fc="#FFF3E0", ec="#E69F00")
    box(0.54, 0.62, 0.20, 0.26, "Policy improvement\nscalar Hamiltonian\n"
        "$\\min_{a\\in\\mathcal{A}(s)}$, piecewise\nexact solver",
        fc="#FFF8E1", ec="#D55E00")
    box(0.80, 0.62, 0.18, 0.26, "Safety projection\n"
        "$\\mathcal{A}(s)\\cap\\mathcal{A}_\\Delta(s)$\n(deployment)",
        fc="#E8F5E9", ec="#009E73")
    box(0.02, 0.06, 0.20, 0.30, "Training points\nfresh Sobol\n(+ adaptive "
        "buffer)\nseed 2101/2201", fc="#F5F5F5", ec="#999999")
    box(0.28, 0.06, 0.20, 0.30, "Tuning-validation\nfrozen Sobol\nseed 3101\n"
        "early stop + selection", fc="#F5F5F5", ec="#999999")
    box(0.54, 0.06, 0.20, 0.30, "Residual-audit design\nfrozen Sobol seed "
        "4101\nNEVER used in training\nevaluated once after freeze",
        fc="#FDECEA", ec="#D55E00")
    box(0.80, 0.06, 0.18, 0.30, "Residual expression\n$2e_T+T(R^{\\pi}+R^{*})$\n"
        "+ Lipschitz-corrected\nsensitivity estimate",
        fc="#FDECEA", ec="#882255")

    # forward chain along the top row
    arrow([(0.22, 0.75), (0.28, 0.75)])
    arrow([(0.48, 0.75), (0.54, 0.75)])
    arrow([(0.74, 0.75), (0.80, 0.75)])
    # policy loop: improvement -> evaluation, routed above the top row;
    # label centred above the horizontal segment of this arrow only
    arrow([(0.64, 0.88), (0.64, 0.97), (0.12, 0.97), (0.12, 0.88)],
          "$\\pi_{n+1}$ (loop)", seg=1, side=+1)
    # point sets feeding the loop
    arrow([(0.08, 0.36), (0.08, 0.62)])                    # training points
    arrow([(0.38, 0.36), (0.38, 0.50), (0.17, 0.50), (0.17, 0.62)],
          "stopping test", seg=1, side=+1)                 # tuning-validation
    arrow([(0.64, 0.36), (0.64, 0.50), (0.89, 0.50), (0.89, 0.62)])
    arrow([(0.74, 0.21), (0.80, 0.21)])
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.06)
    save_figure(fig, "fig02_rv_pinn_pi_workflow",
                {"description": "RV-PINN-PI loop with disjoint point sets",
                 "seeds": {"training": 2101, "adaptive": 2201,
                           "tuning_validation": 3101,
                           "residual_audit": 4101}})


# ----------------------------------------------------------------------
def fig03():
    path = os.path.join(RAW, "expA", "fig3_surfaces.npz")
    if not os.path.exists(path):
        skipped.append("fig03 (no expA surfaces)")
        return
    d = np.load(path)
    s, y = d["s"], d["y"]
    panels = [("V_fd", "FD value", "V"), ("V_direct_hjb", "Direct HJB-PINN value", "V"),
              ("V_rvpinnpi", "RV-PINN-PI value", "V"),
              ("A_fd", "FD policy", "A"), ("A_direct_hjb", "Direct HJB-PINN policy", "A"),
              ("A_rvpinnpi", "RV-PINN-PI policy", "A")]
    vmin_v = min(d[k].min() for k, _, tp in panels if tp == "V" and k in d)
    vmax_v = max(d[k].max() for k, _, tp in panels if tp == "V" and k in d)
    vmax_a = max(abs(d[k]).max() for k, _, tp in panels if tp == "A" and k in d)
    fig, axes = plt.subplots(2, 3, figsize=(7.2, 4.6), sharex=True,
                             sharey=True)
    letters = "abcdef"
    for i, (key, title, tp) in enumerate(panels):
        ax = axes[i // 3, i % 3]
        if key not in d:
            ax.axis("off")
            continue
        if tp == "V":
            # explicit shared level array => genuinely common color scale
            lv = np.linspace(vmin_v, vmax_v, 21)
            im = ax.contourf(y, s, np.clip(d[key], vmin_v, vmax_v),
                             levels=lv, cmap="viridis")
        else:
            lv = np.linspace(-vmax_a, vmax_a, 21)
            im = ax.contourf(y, s, np.clip(d[key], -vmax_a, vmax_a),
                             levels=lv, cmap="RdBu_r")
        ax.set_title(title)
        panel_label(ax, letters[i])
        if i % 3 == 0:
            ax.set_ylabel("SoC $s$")
        if i // 3 == 1:
            ax.set_xlabel("$y$ (kW)")
        # colorbar label only on the last column, so it cannot be read as
        # the y-label of the neighbouring panel (third revision)
        fig.colorbar(im, ax=ax, shrink=0.85,
                     label=("currency" if tp == "V" else "kW")
                     if i % 3 == 2 else None)
    df = pd.DataFrame({"s": np.repeat(s, len(y)),
                       "y": np.tile(y, len(s)),
                       **{k: d[k].ravel() for k, _, _ in panels if k in d}})
    save_figure(fig, "fig03_fd_verification_value_policy", df)


def fig04(master):
    df = master[(master["experiment"] == "expA_fd_verification")
                & (master["policy_iteration"] >= 0)
                & (master["method"] == "rvpinnpi")]
    if len(df) == 0:
        skipped.append("fig04 (no per-iteration expA rows)")
        return
    piv = df.pivot_table(index=["method_seed", "policy_iteration"],
                         columns="metric", values="value", aggfunc="first"
                         ).reset_index()
    fig, axes = plt.subplots(2, 2, figsize=(7.2, 5.0))
    specs = [("train_rms_residual", "Training RMS residual (currency/h)",
              True), ("val_max_residual",
                      "Validation max residual", True),
             ("cost_gap_eJ", "Realized FD policy gap $e_J$ (currency)",
              True), ("rollout_cost", "Estimated policy cost (CRN rollouts)",
                      False)]
    letters = "abcd"
    for i, (metric, ylabel, logy) in enumerate(specs):
        ax = axes[i // 2, i % 2]
        if metric not in piv.columns:
            ax.axis("off")
            continue
        for seed, sub in piv.groupby("method_seed"):
            sub = sub.sort_values("policy_iteration")
            vals = sub[metric]
            if logy:
                vals = vals.clip(lower=1e-12)
            ax.plot(sub["policy_iteration"], vals, color="#D55E00",
                    alpha=0.25, lw=0.8)
        med = piv.groupby("policy_iteration")[metric].median()
        q1 = piv.groupby("policy_iteration")[metric].quantile(0.25)
        q3 = piv.groupby("policy_iteration")[metric].quantile(0.75)
        if logy:
            med, q1, q3 = (v.clip(lower=1e-12) for v in (med, q1, q3))
        ax.plot(med.index, med.values, color="#D55E00", lw=1.8,
                marker="o", label="median")
        ax.fill_between(med.index, q1.values, q3.values, color="#D55E00",
                        alpha=0.2, label="IQR")
        if logy:
            ax.set_yscale("log")
        ax.set_xlabel("Policy iteration $n$")
        ax.set_ylabel(ylabel, fontsize=7.5)
        panel_label(ax, letters[i])
        if i == 0:
            ax.legend()
    save_figure(fig, "fig04_pi_convergence_residual_gap", piv)


def fig05():
    import glob
    cands = sorted(glob.glob(os.path.join(RAW, "expB",
                                          "fig5_trajectories*.npz")))
    cands = [c for c in cands if "minitest" not in c] or cands
    if not cands:
        skipped.append("fig05 (no trajectories)")
        return
    d = np.load(cands[-1], allow_pickle=True)
    seasons = [k.split("__")[1] for k in d.files if k.startswith("meta__")]
    dates = {k.split("__")[1]: str(d[k][0]) for k in d.files
             if k.startswith("meta__")}
    if not dates:
        skipped.append("fig05 (empty meta)")
        return
    methods = sorted({k.split("__")[0] for k in d.files
                      if not k.startswith("meta__")})
    cols = list(dates.items())
    fig, axes = plt.subplots(5, len(cols), figsize=(7.2, 8.2), sharex=True,
                             squeeze=False)
    letters = "abcdefghij"
    ncols = len(cols)
    for c, (season, date) in enumerate(cols):
        ref_m = methods[0]
        t = d[f"{ref_m}__{date}__t"]
        N = d[f"{ref_m}__{date}__N"]
        C = d[f"{ref_m}__{date}__C"]
        ax = axes[0][c]
        ax.plot(t, N, color="#333333", label="net load $N$")
        ax.axhline(0, color="#999999", lw=0.6)
        ax.set_title(f"{season} — {date}")
        ax.set_ylabel("kW" if c == 0 else "")
        panel_label(ax, letters[0 * ncols + c])
        if c == 0:
            ax.legend()
        ax = axes[1][c]
        ax.plot(t, C, color="#882255")
        ax.set_ylabel("price (currency/kWh)" if c == 0 else "")
        panel_label(ax, letters[1 * ncols + c])
        ax = axes[2][c]
        for m in methods:
            key = f"{m}__{date}__a"
            if key in d.files:
                st = sty(m)
                ax.step(t, d[key], where="post", color=st["color"],
                        ls=st["ls"], label=st["label"])
        ax.set_ylabel("action $A$ (kW)" if c == 0 else "")
        panel_label(ax, letters[2 * ncols + c])
        if c == 0:
            ax.legend()
        ax = axes[3][c]
        for m in methods:
            key = f"{m}__{date}__s"
            if key in d.files:
                st = sty(m)
                ax.plot(t, d[key], color=st["color"], ls=st["ls"])
        ax.axhline(0.9, color="k", lw=0.7, ls=":")
        ax.axhline(0.1, color="k", lw=0.7, ls=":")
        ax.set_ylabel("SoC" if c == 0 else "")
        ax.set_ylim(0, 1)
        panel_label(ax, letters[3 * ncols + c])
        ax = axes[4][c]
        for m in methods:
            key = f"{m}__{date}__G"
            if key in d.files:
                st = sty(m)
                ax.step(t, d[key], where="post", color=st["color"],
                        ls=st["ls"])
        ax.axhline(0, color="#999999", lw=0.6)
        ax.set_ylabel("grid $G$ (kW)" if c == 0 else "")
        ax.set_xlabel("hour of day")
        panel_label(ax, letters[4 * ncols + c])
    rows = []
    for c, (season, date) in enumerate(cols):
        for m in methods:
            for var in ("t", "s", "a", "G", "N", "C"):
                key = f"{m}__{date}__{var}"
                if key in d.files:
                    for i, v in enumerate(d[key]):
                        rows.append({"season": season, "date": date,
                                     "method": m, "var": var, "idx": i,
                                     "value": float(v)})
    save_figure(fig, "fig05_daily_dispatch_winter_summer",
                pd.DataFrame(rows))


def fig06(master):
    df = master[(master["experiment"] == "expB_operation")
                & (master["split"] == "test")
                & (master["region"] == "primary")]
    if len(df) == 0 or "rvpinnpi" not in df["method"].unique():
        skipped.append("fig06 (no expB test rows)")
        return
    def day_means(metric):
        sub = df[df["metric"] == metric]
        return sub.groupby(["method", "date"])["value"].mean().unstack("date")
    bills = day_means("bill")
    common = bills.columns[bills.notna().all(axis=0)]
    ref = bills.loc["rvpinnpi", common]
    fig, axes = plt.subplots(2, 2, figsize=(7.2, 5.4))
    ax = axes[0, 0]
    ms = [m for m in bills.index if m != "rvpinnpi"]
    data = [(bills.loc[m, common] - ref).values for m in ms]
    bp = ax.boxplot(data, labels=[sty(m)["label"] for m in ms], vert=False,
                    showfliers=False, patch_artist=True, widths=0.6)
    for patch, m in zip(bp["boxes"], ms):
        patch.set_facecolor(sty(m)["color"])
        patch.set_alpha(0.6)
    ax.axvline(0, color="k", lw=0.8)
    ax.set_xlabel("daily bill $-$ RV-PINN-PI (currency)")
    ax.tick_params(axis="y", labelsize=6.5)
    panel_label(ax, "a")
    ax = axes[0, 1]
    peak = day_means("peak_import_kw")
    for m in peak.index:
        st = sty(m)
        ax.hist(peak.loc[m].dropna().values, bins=25, histtype="step",
                color=st["color"], ls=st["ls"], label=st["label"],
                density=True)
    ax.set_xlabel("daily peak import (kW)")
    ax.set_ylabel("density")
    panel_label(ax, "b")
    ax.legend(fontsize=6.5)  # nine entries; 6.5pt floor shared with category ticks
    ax = axes[1, 0]
    efc = day_means("efc")
    ms2 = [m for m in efc.index]
    ax.boxplot([efc.loc[m].dropna().values for m in ms2],
               labels=[sty(m)["label"] for m in ms2], showfliers=False)
    ax.set_ylabel("equivalent full cycles / day")
    # third revision (Reviewer 1, Comment 1): 45-degree right-anchored
    # ticks so the rotated method names stay clear of the panel label;
    # the (c)/(d) labels themselves are placed further below at one
    # common height (see end of function)
    ax.tick_params(axis="x", rotation=45, labelsize=6.5)
    plt.setp(ax.get_xticklabels(), ha="right", rotation_mode="anchor")
    ax = axes[1, 1]
    lat = day_means("latency_mean_ms")
    for m in lat.index:
        st = sty(m)
        vals = lat.loc[m].dropna().values
        vals = vals[vals > 0]
        if len(vals):
            ax.hist(np.log10(vals), bins=25, histtype="step",
                    color=st["color"], ls=st["ls"])
    ax.set_xlabel("log10 inference latency (ms)")
    ax.set_ylabel("count")
    # bottom-row labels (c)/(d) at one common height, below the deepest
    # decoration of the row (the rotated method names of panel (c))
    fig.canvas.draw()
    ylab = min(axes[1, 0].get_position().y0,
               axes[1, 1].get_position().y0) - 0.145
    for ax_, lt in ((axes[1, 0], "c"), (axes[1, 1], "d")):
        p = ax_.get_position()
        fig.text(p.x0 + p.width / 2, ylab, f"({lt})", ha="center",
                 va="top", fontsize=9, fontweight="bold")
    long = df[df["metric"].isin(["bill", "peak_import_kw", "efc",
                                 "latency_mean_ms"])]
    save_figure(fig, "fig06_operational_performance_distributions",
                long[["method", "method_seed", "date", "metric", "value"]])


def fig07(master):
    df = master[master["experiment"] == "expC_robustness"]
    if len(df) == 0:
        skipped.append("fig07 (no expC rows)")
        return
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.6))
    ax = axes[0]
    sub = df[(df["scenario"] == "m_sigma") & (df["metric"] == "objective")]
    for m, s2 in sub.groupby("method"):
        st = sty(m)
        g = s2.groupby("scenario_value")["value"].mean()
        base = g.get(1.0, np.nan)
        ax.plot(g.index, g.values / base if np.isfinite(base) else g.values,
                color=st["color"], ls=st["ls"], marker=st["marker"],
                label=st["label"])
    ax.set_xlabel("innovation multiplier $m_\\sigma$")
    ax.set_ylabel("normalized cost")
    panel_label(ax, "a")
    ax.legend()
    ax = axes[1]
    for mode, ls in (("known", "-"), ("nominal", "--")):
        sub = df[(df["scenario"] == f"capacity_pct_{mode}")
                 & (df["metric"] == "soc_violations")]
        for m, s2 in sub.groupby("method"):
            if m != "rvpinnpi":
                continue
            g = s2.groupby("scenario_value")["value"].mean()
            ax.plot(g.index, g.values, color=sty(m)["color"], ls=ls,
                    marker="o", label=f"RV-PINN-PI ({mode})")
    ax.set_xlabel("capacity error (%)")
    ax.set_ylabel("mean daily SoC violations")
    panel_label(ax, "b")
    ax.legend()
    ax = axes[2]
    sub = df[(df["scenario"] == "price_spike_h") & (df["metric"] == "bill")]
    for m, s2 in sub.groupby("method"):
        st = sty(m)
        g = s2.groupby("scenario_value")["value"].mean()
        ax.plot(g.index, g.values, color=st["color"], ls=st["ls"],
                marker=st["marker"], label=st["label"])
    ax.set_xlabel("price-spike duration (h)")
    ax.set_ylabel("mean daily bill (currency)")
    panel_label(ax, "c")
    save_figure(fig, "fig07_robustness_distribution_shift",
                df[df["metric"].isin(["bill", "objective",
                                      "soc_violations"])]
                [["method", "scenario", "scenario_value", "metric",
                  "value", "date"]])


def fig08(master):
    df = master[(master["experiment"] == "expA_fd_verification")
                & (master["policy_iteration"] >= 0)]
    if len(df) == 0:
        skipped.append("fig08 (no expA iteration rows)")
        return
    piv = df.pivot_table(index=["method", "method_seed",
                                "policy_iteration"],
                         columns="metric", values="value",
                         aggfunc="first").reset_index()
    T = 24.0
    piv["bound_expr"] = T * (piv.get("val_max_residual", np.nan)
                             + piv.get("hjb_max_residual", np.nan))
    piv = piv[np.isfinite(piv["bound_expr"])
              & np.isfinite(piv.get("cost_gap_eJ", np.nan))]
    if len(piv) == 0:
        skipped.append("fig08 (no joint rows)")
        return
    piv["eJ_pos"] = piv["cost_gap_eJ"].clip(lower=1e-10)
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.6))
    ax = axes[0]
    for m, sub in piv.groupby("method"):
        st = sty(m)
        ax.scatter(sub["eJ_pos"], sub["bound_expr"], s=14,
                   color=st["color"], marker=st["marker"] or "o",
                   label=st["label"], alpha=0.8)
    lims = [min(piv["eJ_pos"].min(), piv["bound_expr"].min()) * 0.5,
            max(piv["eJ_pos"].max(), piv["bound_expr"].max()) * 2]
    ax.plot(lims, lims, "k--", lw=0.8, label="$y=x$")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("realized gap $e_J$ (currency)")
    ax.set_ylabel("$T(\\widehat R^{\\pi}_\\infty+\\widehat R^{*}_\\infty)$"
                  "\n(empirical estimate)", fontsize=7.5)
    panel_label(ax, "a")
    ax.legend()
    ax = axes[1]
    eff = piv["bound_expr"] / piv["eJ_pos"]
    ax.hist(np.log10(eff), bins=25, color="#D55E00", alpha=0.75)
    ax.set_xlabel("log10 effectivity index")
    ax.set_ylabel("count")
    panel_label(ax, "b")
    ax = axes[2]
    from scipy.stats import spearmanr
    metrics = [("train_rms_residual", "train RMS"),
               ("val_max_residual", "val max"),
               ("bound_expr", "bound expr")]
    vals, names = [], []
    for col, nm in metrics:
        if col in piv.columns:
            ok = np.isfinite(piv[col])
            r, _ = spearmanr(piv.loc[ok, col], piv.loc[ok, "eJ_pos"])
            vals.append(r)
            names.append(nm)
    ax.barh(names, vals, color=["#999999", "#0072B2", "#D55E00"][:len(vals)])
    ax.set_xlabel("Spearman corr. with $e_J$")
    ax.set_xlim(-1, 1)
    ax.axvline(0, color="k", lw=0.8)
    panel_label(ax, "c")
    save_figure(fig, "fig08_residual_certificate_effectivity", piv)


# ------------------------- supplementary ------------------------------
def figS01():
    path = os.path.join(RAW, "expA", "fig3_surfaces.npz")
    if not os.path.exists(path):
        skipped.append("figS01")
        return
    d = np.load(path)
    s, y = d["s"], d["y"]
    fig, axes = plt.subplots(2, 2, figsize=(7.2, 5.2))
    items = [("V_direct_hjb", "V_fd", "|direct HJB $-$ FD| value"),
             ("V_rvpinnpi", "V_fd", "|RV-PINN-PI $-$ FD| value"),
             ("A_direct_hjb", "A_fd", "|direct HJB $-$ FD| policy"),
             ("A_rvpinnpi", "A_fd", "|RV-PINN-PI $-$ FD| policy")]
    for i, (k1, k0, title) in enumerate(items):
        ax = axes[i // 2, i % 2]
        if k1 not in d.files:
            ax.axis("off")
            continue
        err = np.abs(d[k1] - d[k0])
        im = ax.contourf(y, s, err, levels=21, cmap="magma")
        ax.set_title(title)
        fig.colorbar(im, ax=ax, shrink=0.85)
        panel_label(ax, "abcd"[i])
    save_figure(fig, "figS01_fd_absolute_error_maps",
                {"source": "fig3_surfaces.npz"})


def figS02():
    path = os.path.join(RAW, "expA", "fd_convergence.json")
    if not os.path.exists(path):
        skipped.append("figS02")
        return
    conv = json.load(open(path))
    fig, ax = plt.subplots(figsize=(3.5, 2.6))
    ax.semilogy([c["grid"] for c in conv],
                [c["linf_vs_finest"] for c in conv], "o-",
                color="#0072B2", label="$L^\\infty$ vs finest")
    ax.semilogy([c["grid"] for c in conv],
                [c["rmse_vs_finest"] for c in conv], "s--",
                color="#D55E00", label="RMSE vs finest")
    ax.set_xlabel("grid")
    ax.set_ylabel("difference (currency)")
    ax.legend()
    save_figure(fig, "figS02_fd_grid_convergence", conv)


def figS03(master):
    df = master[(master["experiment"] == "expA_fd_verification")
                & (master["policy_iteration"] >= 0)]
    if len(df) == 0:
        skipped.append("figS03")
        return
    piv = df.pivot_table(index=["method", "method_seed",
                                "policy_iteration"],
                         columns="metric", values="value",
                         aggfunc="first").reset_index()
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.6))
    for (ax, met, title), letter in zip(
            ((axes[0], "wall_s", "wall time per iteration"),
             (axes[1], "greedy_error", "greedy error (currency/h)")),
            "ab"):
        if met not in piv.columns:
            ax.axis("off")
            continue
        for m, sub in piv.groupby("method"):
            st = sty(m)
            g = sub.groupby("policy_iteration")[met].median()
            ax.plot(g.index, g.values, color=st["color"], ls=st["ls"],
                    marker=st["marker"], label=st["label"])
        ax.set_xlabel("policy iteration")
        panel_label(ax, letter)
        ax.set_title(title)
        ax.legend()
    save_figure(fig, "figS03_training_diagnostics", piv)


def figS04():
    from src.config import ModelParams
    from src.dynamics import soc_step
    from src.safety import project_action_to_safe_set
    p = ModelParams()
    rng = np.random.default_rng(20260731)
    n = 1_000_000
    s = rng.uniform(p.s_min, p.s_max, n)
    a_raw = rng.uniform(-3 * p.a_c, 3 * p.a_d, n)
    a = project_action_to_safe_set(a_raw, s, p, p.dt_ctrl)
    s_next = soc_step(s, a, p.dt_ctrl, p)
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.6))
    axes[0].hist(s_next, bins=100, color="#0072B2", alpha=0.8)
    axes[0].axvline(p.s_min, color="k", ls=":")
    axes[0].axvline(p.s_max, color="k", ls=":")
    axes[0].set_xlabel("next-step SoC after projection (1M random pairs)")
    axes[0].set_ylabel("count")
    panel_label(axes[0], "a")
    axes[1].scatter(s[:5000], a[:5000], s=1, alpha=0.3, color="#D55E00")
    axes[1].set_xlabel("SoC $s$")
    axes[1].set_ylabel("projected action (kW)")
    panel_label(axes[1], "b")
    viol = int(((s_next < p.s_min - 1e-12)
                | (s_next > p.s_max + 1e-12)).sum())
    save_figure(fig, "figS04_soc_safety_stress_test",
                {"n_samples": n, "violations": viol, "seed": 20260731})


def figS05(master):
    df = master[master["experiment"] == "expC_robustness"]
    if len(df) == 0:
        skipped.append("figS05")
        return
    sub = df[df["metric"] == "bill"]
    g = sub.groupby(["scenario", "scenario_value", "method"])[
        "value"].mean().reset_index()
    g["col"] = g["scenario"] + "=" + g["scenario_value"].round(2).astype(str)
    piv = g.pivot_table(index="method", columns="col", values="value")
    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    im = ax.imshow(piv.values, aspect="auto", cmap="viridis")
    ax.set_yticks(range(len(piv.index)))
    ax.set_yticklabels([sty(m)["label"] for m in piv.index], fontsize=6.5)
    ax.set_xticks(range(len(piv.columns)))
    ax.set_xticklabels(piv.columns, rotation=90, fontsize=6.5)
    fig.colorbar(im, ax=ax, label="mean daily bill")
    save_figure(fig, "figS05_full_robustness_matrix",
                piv.reset_index())


def figS06(master):
    df = master[master["experiment"] == "expD_ablations"]
    if len(df) == 0:
        skipped.append("figS06")
        return
    sub = df[df["metric"].isin(["value_rmse", "cost_gap_eJ", "bill",
                                "soc_violations", "rollout_cost"])]
    g = sub.groupby(["scenario", "metric"])["value"].mean().reset_index()
    piv = g.pivot_table(index="scenario", columns="metric", values="value")
    norm = (piv - piv.min()) / (piv.max() - piv.min() + 1e-12)
    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    im = ax.imshow(norm.values, aspect="auto", cmap="RdYlGn_r")
    ax.set_yticks(range(len(norm.index)))
    ax.set_yticklabels(norm.index, fontsize=6.5)
    ax.set_xticks(range(len(norm.columns)))
    ax.set_xticklabels(norm.columns, rotation=45, fontsize=6.5)
    fig.colorbar(im, ax=ax, label="normalized (per metric)")
    save_figure(fig, "figS06_ablation_heatmap", piv.reset_index())


def figS07(master):
    df = master[(master["experiment"] == "expC_robustness")
                & (master["scenario"] == "external_region")
                & (master["metric"] == "bill")]
    if len(df) == 0:
        skipped.append("figS07")
        return
    g = df.groupby("method")["value"].agg(["mean", "std"])
    fig, ax = plt.subplots(figsize=(3.5, 2.6))
    colors = [sty(m)["color"] for m in g.index]
    ax.bar([sty(m)["label"] for m in g.index], g["mean"], yerr=g["std"],
           color=colors, alpha=0.8)
    ax.set_ylabel("mean daily bill (EUR)")
    ax.tick_params(axis="x", rotation=45, labelsize=6.5)
    save_figure(fig, "figS07_external_region_generalization",
                g.reset_index())


def figS08(master):
    df = master[(master["experiment"] == "expD_ablations")
                & (master["scenario"].str.startswith("A10", na=False))]
    if len(df) == 0:
        skipped.append("figS08")
        return
    piv = df.pivot_table(index=["scenario", "method_seed"],
                         columns="metric", values="value",
                         aggfunc="first").reset_index()
    piv["budget"] = piv["scenario"].str.split(":").str[-1].astype(float)
    fig, ax = plt.subplots(figsize=(3.5, 2.6))
    g = piv.groupby("budget")["value_rmse"].agg(["mean", "std"])
    ax.errorbar(g.index, g["mean"], yerr=g["std"], marker="o",
                color="#D55E00")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("collocation budget factor")
    ax.set_ylabel("value RMSE (currency)")
    save_figure(fig, "figS08_compute_scaling", piv)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--allow-new-results", action="store_true")
    ap.add_argument("--only", default=None)
    args = ap.parse_args()
    set_style()
    master = load_master(args.allow_new_results)
    figs = {
        "fig01": fig01, "fig02": fig02, "fig03": fig03,
        "fig04": lambda: fig04(master), "fig05": fig05,
        "fig06": lambda: fig06(master), "fig07": lambda: fig07(master),
        "fig08": lambda: fig08(master),
        "figS01": figS01, "figS02": figS02,
        "figS03": lambda: figS03(master), "figS04": figS04,
        "figS05": lambda: figS05(master), "figS06": lambda: figS06(master),
        "figS07": lambda: figS07(master), "figS08": lambda: figS08(master),
    }
    only = set(args.only.split(",")) if args.only else None
    for name, fn in figs.items():
        if only and name not in only:
            continue
        try:
            fn()
        except Exception as e:
            skipped.append(f"{name} (ERROR: {e})")
            print(f"  {name} FAILED: {e}")
    problems = qa_check()
    report = {"skipped": skipped, "qa_problems": problems}
    with open(os.path.join(ROOT, "paper", "figures", "_figure_qa.json"),
              "w") as f:
        json.dump(report, f, indent=2)
    print("figure QA:", report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
